In [4]:
import numpy as np


In [5]:
myls=[1,2,3,4,5]
type(myls)

list

In [6]:
np.array(myls)

array([1, 2, 3, 4, 5])

In [7]:
myls=[[1,2,2],[1,3,6,]]
df=np.array(myls)
df.shape


(2, 3)

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [13]:
[1,1,1,1]*100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [14]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [15]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(4,4)

array([[0.27949655, 0.23075425, 0.98426829, 0.34293404],
       [0.76582049, 0.44913252, 0.72560524, 0.99915946],
       [0.98214116, 0.70073642, 0.55433868, 0.1879081 ],
       [0.81496152, 0.96252437, 0.316521  , 0.94021475]])

In [24]:
np.random.randn(10)

array([-0.2997857 , -0.65012654, -1.52868884, -0.63803979,  1.73391763,
       -1.00029917,  0.14511179, -1.51437618,  1.21813138,  0.36026439])

In [27]:
np.random.normal(loc=0.2,scale=3.0,size=None)

0.6464431606149978

In [30]:
np.random.randint(1,100,10)

array([60, 53, 80, 59, 72, 38, 36, 24, 85, 47])

In [33]:
np.random.seed(100)
np.random.rand(4)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761])

In [34]:
np.random.rand(4)

array([0.89294695, 0.89629309, 0.12558531, 0.20724288])

In [35]:
arr=np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
rarr=np.random.randint(0,50,10)

In [38]:
rarr

array([38, 32, 20, 44, 29, 39, 14, 26, 17, 26])

In [39]:
arr.shape

(25,)

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
rarr

array([38, 32, 20, 44, 29, 39, 14, 26, 17, 26])

In [46]:
rarr.max()

44

In [47]:
rarr.min()

14

In [48]:
rarr.argmax()
rarr.argmin()

6

In [49]:
rarr

array([38, 32, 20, 44, 29, 39, 14, 26, 17, 26])

In [50]:
rarr.dtype

dtype('int32')

In [51]:
type(rarr)

numpy.ndarray

In [89]:
#indexing and selection
arr=np.arange(0,11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[8]

8

In [92]:
arr[1:5]

array([1, 2, 3, 4])

In [93]:
arr[0:4]

array([0, 1, 2, 3])

In [94]:
arr[:5]

array([0, 1, 2, 3, 4])

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [97]:
new_ar=arr/2
new_ar

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [98]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [99]:
#broadcasting
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
slice_of_arr=arr[0:6]

In [101]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [102]:
slice_of_arr[:]=99

In [103]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [109]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [110]:
arr_copy=arr.copy()

In [116]:
arr2=arr_copy[0:6]

In [117]:
arr2[:]=1000

In [118]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000])

In [119]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000,    6,    7,    8,    9,   10])

In [129]:
#2d indexing
arr=np.arange(1,11)

In [130]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
arr_2d=np.array([[1,2,3],[22,34,46],[36,42,51]])

In [139]:
arr_2d

array([[ 1,  2,  3],
       [22, 34, 46],
       [36, 42, 51]])

In [140]:
arr_2d.shape

(3, 3)

In [141]:
arr_2d[1]

array([22, 34, 46])

In [142]:
arr_2d[1,1]

34

In [143]:
arr_2d[2,2]

51

In [144]:
#selection
arr_2d

array([[ 1,  2,  3],
       [22, 34, 46],
       [36, 42, 51]])

In [146]:
arr_2d[:2,1:]

array([[ 2,  3],
       [34, 46]])

In [147]:
arr_2d[1:,:2]

array([[22, 34],
       [36, 42]])

In [148]:
#codn and selection
arr=np.arange(1,11)

In [149]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [150]:
bool_arr=arr>4

In [151]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [152]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [153]:
arr[arr==2]

array([2])

In [154]:
arr[arr>=6]

array([ 6,  7,  8,  9, 10])

In [156]:
#numpy operation
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [158]:
arr/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [159]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [160]:
arr.dtype

dtype('int32')

In [161]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [162]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [167]:
sarr=arr/arr

In [168]:
sarr.dtype

dtype('float64')

In [169]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [170]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [171]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [172]:
arr.sum()

55

In [173]:
arr.max()

10

In [174]:
arr.min()

1

In [176]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [177]:
arr_2d.shape

(3, 4)

In [178]:
arr_2d.sum()

78

In [179]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
#across the rows means sum of column
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [181]:
arr_2d.sum(axis=1)#across the columns

array([10, 26, 42])

In [182]:
#exercise
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [183]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [190]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [203]:
arr=np.arange(10,50)

In [204]:
boolarr=arr%2==0

In [206]:
boolarr

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False])

In [207]:
arr[boolarr]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [213]:
arr=np.arange(0,9)

In [214]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [215]:
arr_2d=arr.reshape(3,3)

In [217]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [218]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [226]:
np.random.rand(5)

array([0.14259934, 0.30226361, 0.80702268, 0.31949503, 0.02122574])

In [229]:
np.random.seed(25)
np.random.randn(25)

array([ 0.22827309,  1.0268903 , -0.83958485, -0.59118152, -0.9568883 ,
       -0.22232569, -0.61991511,  1.83790458, -2.05323076,  0.86858305,
       -0.92073444, -0.23231186,  2.1529569 , -1.33466147,  0.07637965,
       -1.24608928,  1.20227231, -1.04994158,  1.05661011, -0.41967767,
        2.29484234, -2.59448738,  2.8227564 ,  0.68088892, -1.57769345])

In [245]:
arr=np.arange(1,101)/100

In [249]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [251]:
np.random.rand(20)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [259]:
arr=np.arange(1,26)
arr=arr.reshape(5,5)

In [260]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [262]:
arr[3,4]

20

In [263]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [265]:
arr[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [267]:
arr[4,:5]

array([21, 22, 23, 24, 25])

In [268]:
arr[3:5,:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [269]:
arr.sum()

325

In [270]:
arr.std()

7.211102550927978

In [271]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [272]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [276]:
#same random no
np.random.seed(101)
np.random.rand(1)

array([0.51639863])